name: provision_on_create

on:
  create:
    branches:
      - 'waqa/**'

jobs:
  provision_cluster:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      VERSION_GRAALVM: 21.2.0

    steps:
      - uses: actions/checkout@v2
      
      - uses: nelonoel/branch-name@v1.0.1

      - name: generate Unique id
        run: echo UNIQ_ID=${BRANCH_NAME/\//-} >> $GITHUB_ENV

      - name: check unique id
        run: echo ${{ env.UNIQ_ID }}

      - name: Download rosa binary
        run: |
          wget -q -O /tmp/rosa-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/rosa/latest/rosa-linux.tar.gz
          tar zxvf /tmp/rosa-linux.tar.gz -C  /tmp/
          sudo mv /tmp/rosa /usr/local/bin/ 
          rm /tmp/rosa-linux.tar.gz

      - name: Check rosa binary
        run: rosa version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.OCP_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OCP_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Create IAM User
        run: aws iam create-user --user-name ${{ env.UNIQ_ID }}
      
      - name: Wait for IAM User
        run: aws iam wait user-exists --user-name ${{ env.UNIQ_ID }}

      - name: Grant install privileges
        run: |
            aws iam attach-user-policy \
              --user-name ${{ env.UNIQ_ID }} \
              --policy-arn ${{ env.POLICY_ARN }}
        env:
          POLICY_ARN: "arn:aws:iam::aws:policy/AdministratorAccess"

      - name: Create install user credentials
        run: aws iam create-access-key --user-name ${{ env.UNIQ_ID }} --query "AccessKey" > ak.json
      
      - name: Wait for credentials
        run: sleep 5

      - name: Mask AK_ID
        run: echo "::add-mask::$(jq -r ".AccessKeyId" ak.json)"

      - name: Mask SK_ID
        run: echo "::add-mask::$(jq -r ".SecretAccessKey" ak.json)"

      - name: Export AK_ID
        run: echo NEW_ACCESS_KEY_ID="$(jq -r ".AccessKeyId" ak.json)" >> $GITHUB_ENV

      - name: Export SK_ID
        run: echo NEW_SECRET_ACCESS_KEY=$(jq -r ".SecretAccessKey" ak.json) >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.NEW_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.NEW_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check new identity
        run: aws sts get-caller-identity

      - name: Login to ROSA
        run: rosa login --token=${{ env.ROSA_TOKEN }}

      - name: Verify ROSA permissions
        run: rosa verify permissions

      - name: Verify OC client
        run: rosa verify oc

      - name: Verify ROSA quotas
        run: rosa verify quota --region=${{ env.AWS_REGION }}
      
      - name: Verify ROSA identity
        run: rosa whoami
      
      - name: Init ROSA
        run: rosa init

      - name: Create ROSA cluster
        run: echo rosa create cluster 

      