name: deploy_on_branch

on:
  create:
    branches:
      - 'waqa/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      VERSION_GRAALVM: 21.2.0

    steps:
      - uses: actions/checkout@v2
      
      - uses: nelonoel/branch-name@v1.0.1

      - name: generate Unique id
        run: echo UNIQ_ID=${BRANCH_NAME/\//-} >> $GITHUB_ENV

      - name: check unique id
        run: echo ${{ env.UNIQ_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Provision ROSA Cluster
        run: echo provisioning rosa cluster
      
      

