name: provision_on_create

on:
  create:
    branches:
      - 'waqa/**'

jobs:
  provision_cluster:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      VERSION_GRAALVM: 21.2.0

    steps:
      - uses: actions/checkout@v2
      
      - uses: nelonoel/branch-name@v1.0.1

      - name: generate Unique id
        run: echo UNIQ_ID=${BRANCH_NAME/\//-} >> $GITHUB_ENV

      - name: check unique id
        run: echo ${{ env.UNIQ_ID }}

      - name: Download rosa binary
        run: |
          wget -q -O /tmp/rosa-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/rosa/latest/rosa-linux.tar.gz
          tar zxvf /tmp/rosa-linux.tar.gz -C  /tmp/
          sudo mv /tmp/rosa /usr/local/bin/ 
          rm /tmp/rosa-linux.tar.gz

      - name: Check rosa binary
        run: rosa version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.OCP_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.OCP_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Check AWS authentication
        run: aws sts get-caller-identity

      - name: Login to ROSA
        run: rosa login --token=${{ secrets.ROSA_TOKEN }}

      - name: Verify ROSA permissions
        run: rosa verify permissions

      - name: Verify OC client
        run: rosa verify oc

      - name: Verify ROSA quotas
        run: rosa verify quota --region=${{ env.AWS_REGION }}
      
      - name: Verify ROSA identity
        run: rosa whoami
      
      - name: Init ROSA
        run: rosa init

      - name: Create ROSA cluster
        run: rosa create cluster --cluster-name=${{ env.UNIQ_ID }}
      
      - name: Wait until cluster is ready
        run: |
          CLUSTER_STATE="installing"
          until [ $CLUSTER_STATE != "installing" ]
          do
              CLUSTER_STATE=$(rosa describe cluster -c ${{ env.UNIQ_ID }} -o json | jq -r ".status.state")
              echo Cluster is $CLUSTER_STATE on $(date)
              sleep 30
          done

      - name: Nest step
        run: echo next step


